Fix min n max
max-mykhailenko/react-pure-datepicker pull request #11
Opened 2017-10-27 14:01 UTC by kramarmm

2017-10-27 15:32 UTC, max-mykhailenko requested changes

2017-10-27 15:32 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +        this.setState({ value: instadate.addDays(min, 1) });
а почему следующий от минимальной даты? Лучше минимальную, так как следующая может уже не входить в max лимит

2017-10-27 15:37 UTC, kramarmm commented on src/react-pure-datepicker.js
> +        this.setState({ value: instadate.addDays(min, 1) });
минимальная не входит

2017-10-27 15:42 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +        this.setState({ value: instadate.addDays(min, 1) });
Давай сделаем чтобы min и max входили в возможные значения, это более правильно

2017-10-31 15:51 UTC, max-mykhailenko requested changes

2017-10-31 15:51 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +    this.state = this.setComponentState();
Лучше делать `getComponentState()`

2017-10-31 15:51 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +    this.setComponentState(nextProps);
и здесь делать setState и в него сунуть `setComponentState()`

2017-10-31 15:51 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +        this.setState(updatedState);
Свести все с return

2017-10-31 15:51 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +    const isInitialSetState = !nextProps.value;
Тоже можно убрать

2017-10-31 15:54 UTC, max-mykhailenko commented on src/react-pure-datepicker.js
> +            updatedState.value = instadate.addDays(updatedState.min, 1);
Давай включительно с днями работать, т.е. min может быть равно value

2017-11-01 08:07 UTC, merged